Repository eli64s/readme-ai, pull requests merged in 2023-09, with the labels that each got.

#52 feature: Add CLI option to run in offline mode.
  .github/release-drafter.yml
  CHANGELOG.md
  README.md
  pyproject.toml
  readmeai/builder.py
  readmeai/conf.py
  readmeai/conf/conf.toml
  readmeai/main.py
Labels: enhancement, feature

#53 [FIX] Implement Custom Directory Tree Method
  README.md
  pyproject.toml
  readmeai/builder.py
  readmeai/main.py
  readmeai/preprocess.py
  readmeai/utils.py
  scripts/clean.sh
Labels: bug, enhancement

#54 Codebase Clean Up
  .github/workflows/build_image.yml
  .github/workflows/publish_package.yml
  CHANGELOG.md
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  readmeai/builder.py
  readmeai/conf/conf.toml
  readmeai/conf/ignore_files.toml
  readmeai/main.py
  readmeai/model.py
  readmeai/utils.py
Labels: maintenance

#42 Setupfix
  readmeai/main.py
  scripts/build_pypi.sh
  setup/setup.sh
Labels: enhancement

#57 Decouple CLI
  README.md
  readme-ai.md
  readmeai/main.py
  readmeai/model.py
Labels: chore
